name: Auto-apply PR template by directory
on:
  pull_request:
    types: [opened]

jobs:
  detect-directory:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.changes.outputs.frontend }}
      backend: ${{ steps.changes.outputs.backend }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Detect which directory changed
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            frontend:
              - 'web-front/**'
            backend:
              - 'backend/**'

  apply-template:
    runs-on: ubuntu-latest
    needs: detect-directory
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Apply frontend template
        if: needs.detect-directory.outputs.frontend == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const template = fs.readFileSync('.github/PULL_REQUEST_TEMPLATE/frontend.md', 'utf8');
            github.rest.pulls.update({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: template
            });
      
      - name: Apply backend template
        if: needs.detect-directory.outputs.backend == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const template = fs.readFileSync('.github/PULL_REQUEST_TEMPLATE/backend.md', 'utf8');
            github.rest.pulls.update({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: template
            });
